//////////////////////////////////////////////////////////////////////////////////////
//    akashi - a server for Attorney Online 2                                       //
//    Copyright (C) 2020  scatterflower                                             //
//                                                                                  //
//    This program is free software: you can redistribute it and/or modify          //
//    it under the terms of the GNU Affero General Public License as                //
//    published by the Free Software Foundation, either version 3 of the            //
//    License, or (at your option) any later version.                               //
//                                                                                  //
//    This program is distributed in the hope that it will be useful,               //
//    but WITHOUT ANY WARRANTY; without even the implied warranty of                //
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                 //
//    GNU Affero General Public License for more details.                           //
//                                                                                  //
//    You should have received a copy of the GNU Affero General Public License      //
//    along with this program.  If not, see <https://www.gnu.org/licenses/>.        //
//////////////////////////////////////////////////////////////////////////////////////
#ifndef MUSIC_MANAGER_H
#define MUSIC_MANAGER_H

#include <QObject>
#include <QMap>
#include <QHash>
#include <QPair>

class MusicManager : public QObject
{
    Q_OBJECT
public:

    /**
     * @brief Constructor for the server-wide musiclist manager.
     *
     * @param Copy of the server musiclist generated by ConfigManager::musiclist();
     */
    MusicManager(QMap<QString,QPair<QString,float>> f_root_list);

    /**
     * @brief Destructor for the server-wide musiclist manager.
     */
    virtual ~MusicManager();

    bool validateSong(QString f_song_name, QStringList f_approved_cdns);

private:

    /**
     * @brief God has left us. Sometimes I wonder if he looks at this code and screams.
     */
    QHash<int,QMap<QString,QPair<QString,float>>>* m_custom_lists;

    /**
     * @brief Server-Wide musiclist shared among all areas. Prepend to the custom list if enabled.
     */
    QMap<QString,QPair<QString,float>> m_root_list;
};

#endif // MUSIC_MANAGER_H
