name: CI

# Runs on pushes and pull requests for the master branch
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  formatting-check:
    name: check-clang-format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run clang-format style check.
      uses: jidicula/clang-format-action@v4.5.0
      with:
        clang-format-version: '16'
        check-path: '.'

  build-linux:
    needs: formatting-check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          aqtversion: '==3.1.*'
          version: '6.5.3'
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'
          cache: true
          cache-key-prefix: install-qt-action
          modules: 'qtwebsockets'

      - name: Configure
        run: cmake -B build -D CMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Test
        run: ctest --test-dir build --output-on-failure

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: akashi-linux
          path: bin/

  build-windows:
    needs: formatting-check
    if: always()
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.5.3
          target: desktop
          arch: win64_msvc2019_64
          cache: true
          cache-key-prefix: install-qt-action
          modules: 'qtwebsockets'

      - name: Configure
        run: cmake -B build -D CMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Test
        run: ctest --test-dir build -C Release --output-on-failure

      - name: Deploy
        run: windeployqt bin\akashi.exe --release --no-translations --no-compiler-runtime --no-opengl-sw

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: akashi-windows
          path: bin\
